version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  spark:
    image: bitnami/spark:3.0.1
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"

  python-app:
    build: .
    volumes:
      - ./data:/app/data/archive  # Ensure this line maps the local 'data/' directory to the container
    depends_on:
      - kafka
      - spark
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: bash /app/scripts/run.sh
